### PR TITLE
added frameBorder=0 to the shinyframe iframe

### PR DESCRIPTION
**Pull request by oflasch**
We had the problem that Apple Safari Version 11.0.3 (12604.5.6.1.1) displays a 1-pixel-wide border around the shiny app. Adding frameBorder="0" to the shinyframe iframe fixes that.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
I'm assuming the "Login auf deutsch" commit wasn't meant for this PR.

**Comment by oflasch** [comment]
Sure, sorry for that mistake. 

Kind regards 
Oliver

-- 
Oliver Flasch

**Comment by fmichielssen** [comment]
Hi @oflasch ,

Thanks for this PR. It seems to happen in other browsers as well.
Just one remark: the 'frameBorder' attribute appears to be deprecated. Could you provide a css-based approach instead, please?

**Comment by oflasch** [comment]
I just added a css-based approach. I also kept the frameBorder attribute, as it seems to be required for Internet Explorer 11 compatibility ( see https://stackoverflow.com/questions/3601273/html5-and-frameborder ).

**Pull request merged**
