### PR TITLE
Fix multiple session IDs for one user

### LINKED ISSUE #35: 'No Session ID Found' when use another browser or after the session expired
I'm using the latest ShinyProxy 1.0.2 and is experiencing an issue where after opening an app in one browser and then try using another browser to access the same app, the page only shows 'No session ID found'.

After a while, I guess when the session does expire, even using the original browser will have the same issue.

### PR DESCRIPTION
**Pull request by PlasmaPower**
Fixes #35

### CODE REVIEW

**Comment by fmichielssen** [comment]
Before merging, can you please check the following in UserService?

- AppCleaner should iterate over all active proxies, not just those in heartbeatTimestamps.
E.g. browser tabs that crash or close before the app's first heartbeat is received, should also be considered for cleanup.
- heartbeatReceived(String, String): should also register heartbeats for new proxies, that are not yet in heartbeatTimestamps.

**Comment by PlasmaPower** [comment]
Good catches! I checked that timing out actually worked this time.

I also moved the heartbeat timeout management from UserService to DockerService, since it felt like I was replicating a lot of the functionality already there.

**Comment by fmichielssen** [comment]
Hi @PlasmaPower ,

Sorry for the delay. Could you rebase the pr, or merge master into it?

**Comment by PlasmaPower** [comment]
Rebased.

**Comment by fmichielssen** [comment]
Merged - note that the stop-on-logout property has been removed, to ensure the following logic is applied:

* explicit log out: all of the user's active containers are shut down.
* implicit log out: a container is shut down when there are no more heartbeats coming in for that particular user/app container.

Thanks for the contribution, @PlasmaPower !

**Pull request merged**
