### PR TITLE
Template functionality added

### PR DESCRIPTION
**Pull request by ucg8j**
This PR brings in the ability switch bootstrap templates. 

- There are now three templates, the default and two new templates [1-col](https://startbootstrap.com/template-overviews/1-col-portfolio/) and [2-col](https://startbootstrap.com/template-overviews/2-col-portfolio/). These provide a nice UI. 
- These templates provide an image of the application. Therefore, a configuration parameter has been added to the `application.yml` for each app to point to the relevant thumbnail image.
- The additional files were failing the build tests. Hence an exemption of the licence tests has ben added to the `pom.xml`

### CODE REVIEW

**Comment by PlasmaPower** [comment]
Did you try uncommenting the `generate-copyright-headers` execution in the `pom.xml` and seeing if it fixed your licence tests issue? It can be picky about whitespace and such.

**Comment by ucg8j** [comment]
@PlasmaPower - yeah we came across the fiddly nature of the licence tests. However, as we're utilising bootstrap.css, we didn't want to add the shinyproxy licence into bootstrap files. Therefore, we just put file exemptions into the `pom.xml`.

**Comment by fmichielssen** [comment]
Hi @ucg8j ,

Would it be possible to re-submit this PR on the develop branch?
We have changed our branching model a bit on Github, to allow us more flexibility.

Thanks!

**Comment by ucg8j** [comment]
@fmichielssen no worries, will do it now

**Pull request closed without merging**
