### PR TITLE
Add Kubernetes support

### PR DESCRIPTION
**Pull request by PlasmaPower**
Probably conflicts with #33, or at least they don't work right together, but it shouldn't be too hard to fix once one gets merged.

~Watching the logs isn't finished yet, but that shouldn't take terribly long.~ Edit: done.

### CODE REVIEW

**Comment by fmichielssen** [comment]
Hi @PlasmaPower ,

Would it be possible to re-submit this PR on the develop branch?
We have changed our branching model a bit on Github, to allow us more flexibility.

Thanks!

**Comment by PlasmaPower** [comment]
There's no need to resubmit the PR. I've edited both PRs to merge into the develop branh.

**Comment by PlasmaPower** [comment]
Updated to support running in Kubernetes (I've cherry picked changes from our fork).

**Comment by zagorulkinde** [comment]
Hey! @fmichielssen Do you plan on merging this PR into master branch?

**Comment by fmichielssen** [comment]
Hi @zagorulkinde, @PlasmaPower,
Sorry for not responding for so long. Yes, we still want to get this Kubernetes support in. But it will probably not go via this PR, because shinyproxy has been significantly refactored in the meantime.
See here for more details:
https://github.com/openanalytics/shinyproxy/tree/develop/src/main/java/eu/openanalytics/shinyproxy/container/kubernetes
As you can see, the new code is largely based on this PR. Note that it is de develop branch, not master.

**Comment by PlasmaPower** [comment]
Thanks for the update! I guess I'll close this PR then.

**Pull request closed without merging**
